config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books', to: 'books#index'
  get 'books/search', to: 'books#display_search'
  post 'books/search', to: 'books#search'
  post 'books/create', to: 'books#create'
  post 'books/update', to: 'books#status_update'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  get 'users/setting', to: 'users#display_setting'
  patch 'users/setting', to: 'users#update_setting'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :statuses

  def get_max_status
    max_status = self.statuses.order("status_code desc").limit(1)[0]
    max_status.status_code
  end

  def get_lapsed_days(status_code)
    (Time.now - self.statuses.find_by(status_code: status_code).created_at).to_i/(60*60*24)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    # 最も進んだステータスの登録日が古い順にソート
    @books = Book.find_by_sql( \
      ['select b.* from books b, statuses s1
        where b.user_id = ?
        and   b.id = s1.book_id
        and   s1.status_code = (
          select max(status_code) from statuses s2
          where s2.book_id = s1.book_id
          group by s2.book_id
        )
        order by s1.created_at;
        ', current_user.id])

    @books_status_0 = [] # 気になる
    @books_status_3 = [] # 購入済
    @books_status_7 = [] # 読書開始
    @books_status_9 = [] # 読了
    # 最も進んだステータスを取りに行く
    @books.each do |book|
      case book.get_max_status
      when 9 then
        @books_status_9 << book
      when 7 then
        @books_status_7 << book
      when 3 then
        @books_status_3 << book
      when 0 then
        @books_status_0 << book
      else
        # 何もしない
      end
    end
  end

  def display_search
  end

  def search
    # jsでのエラー判別用
    @error_flg = 0

    if params[:title].present? || params[:author].present?
      # デバッグログ出力
      Amazon::Ecs.debug = true

      # 503エラーが理由なくしょっちゅう起きるためリトライする
      retry_count = 0

      begin
        books = Amazon::Ecs.item_search(
          '', #keyword:titleとauthor個別で検索するためブランク
          title: params[:title],
          author: params[:author],
          search_index: 'Books',
          dataType: 'script',
          response_group: 'ItemAttributes, Images',
          country: 'jp',
          power: 'Not kindle'
        )
      rescue
        retry_count += 1
        if retry_count < 5
          sleep(1) # Amazonの設定上1秒待てばいいはずなので1秒だけ待つ
          retry
        else
          flash[:error] = "エラーが発生しました。しばらく置いてから再実行してください。"
          @error_flg = 1
        end
      end

      @books = []
      books.items.each do |item|
        book = Book.new(
          isbn: item.get('ItemAttributes/ISBN'),
          title: item.get('ItemAttributes/Title'),
          author: item.get('ItemAttributes/Author'),
          image_url: item.get('LargeImage/URL'),
          url: item.get('DetailPageURL')
        )
        @books << book
      end
      @totalCount = books.total_results

      # 検索結果0件
      if @totalCount == 0
        flash[:danger] = "条件に該当する本がありません。"
        # 検索結果は返ってくるため、検索結果一覧を再描画するためエラーとしては扱わない
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def create
    logger.debug(params[:status])

    respond_to do |format|
      if Book.find_by(user_id: current_user.id, isbn: params[:isbn]).present?
        #登録済
        logger.debug("登録済")
        flash[:danger] = "本棚に登録済みです"
        format.js
      else
        book = Book.new(
          user_id: current_user.id,
          isbn: params[:isbn],
          title: params[:title],
          author: params[:author],
          image_url: params[:image_url],
          url: params[:url]
        )

        if book.save
          # 登録成功
        else
          # 登録失敗
        end

        status = Status.new(
          book_id: book.id,
          status_code: params[:status]
        )
        if status.save
          # 登録成功
        else
          # 登録失敗
        end
        flash[:success] = "登録しました。"
        format.js
      end
    end
  end


  def status_update
    logger.debug(params[:book_id])

    status = Status.new(
      book_id: params[:book_id],
      status_code: params[:status])
    if status.save
      # 登録成功
    else
      # 登録失敗
    end
    flash[:success] = "更新しました。"
    # TODO 一旦リダイレクトで実装。最終的にはajax化する(一覧部分再描画)
    redirect_to books_path
  end

end

app/views/books/_books.html.erb
<h4>
  <span class="label label-primary"><%=t "label.status.s#{status}"%></span>
</h4>
<%if books.present?%>
  <table class="table table-striped table-fixed">
    <thead>
      <th class="col1"><!--image--></th><th class="col2"><!--タイトル・著者・登録からの日数--></th><th class="col3"><!--status update--></th>
    </thead>
    <tbody>
      <%books.each do |book|%>
        <script type="text/javascript">
        $(function(){
          // 登録からの日数がユーザー設定の日数以上となっている場合、赤太字にする(対象の日数はsendで動的に生成)
          if (parseInt($("span.reg_date_<%=book.id%>").text()) >= <%=current_user.send("alert_days_status_" + status.to_s)%>) {
            $("span.reg_date_<%=book.id%>").parent($('p')).css({
              'color' : 'red',
              'font-weight' : 'bold'
            });
          }
        });
        </script>
        <tr id="book-<%=book.id%>">
          <td>
            <%if book.image_url.present?%>
              <%=link_to (image_tag(book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), book.url%>
            <%else%>
              <%=link_to "no image", book.url%>
            <%end%>
          </td>
          <td>
            <h4><%=book.title%></h4>
            <small><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><%=book.author%></small>
            <p>
              <!-- 読了の場合のみ読了日を表示、他は登録からの日数を表示 -->
              <%if status < 9%>
              「<%=t("label.status.s#{status}")%>」
              登録から
               <span class="reg_date_<%=book.id%>">
                 <%=(Time.now - book.statuses.find_by(status_code: status).created_at).to_i/(60*60*24)%>
               </span>
               日
              <%else%>
                <%=book.statuses.find_by(status_code: status).created_at.to_date.to_s(:default)%>
                <%=t("label.status.s#{status}")%>
              <%end%>
            </p>
          </td>
          <td>
            <%if status < 3%>
              <p>
                <%=link_to t('label.status.s3'), books_update_path(
                  :book_id => book.id,
                  :status => 3), # 購入済
                  :method => :post,
                  data: {confirm: "「#{t('label.status.s3')}」に更新します."},
                  class: 'update_status',
                  remote: true%>
              </p>
            <%end%>
            <%if status < 7%>
              <p>
                <%=link_to t('label.status.s7'), books_update_path(
                  :book_id => book.id,
                  :status => 7), # 読書開始
                  :method => :post,
                  data: {confirm: "「#{t('label.status.s7')}」に更新します."},
                  class: 'update_status',
                  remote: true%>
              </p>
            <%end%>
            <%if status < 9%>
              <p>
                <%=link_to t('label.status.s9'), books_update_path(
                  :book_id => book.id,
                  :status => 9), # 読書開始
                  :method => :post,
                  data: {confirm: "「#{t('label.status.s9')}」に更新します."},
                  class: 'update_status',
                  remote: true%>
              </p>
            <%end%>
          </td>
          </div>
        </tr>
      <%end%>
    </tbody>
  </table>
<%end%>

app/views/books/_books_searched.html.erb
<table class="table table-striped table-fixed">
  <thead>
    <th class="col1"><!--image--></th><th class="col2"><!--タイトル・著者--></th><th class="col4"><!--status update--></th>
  </thead>
  <tbody>
    <%@books.each do |book|%>
      <tr>
        <td>
          <%if book.image_url.present?%>
            <%=link_to (image_tag(book.image_url, style: "width: 35px;height: 50px;display: inline-block;")), book.url%>
          <%else%>
            <%=link_to "no image", book.url%>
          <%end%>
        </td>
        <td>
          <h4><%=book.title%></h4>
          <small><%=book.author%></small>
        </td>
        <td>
          <p>
            <%=link_to t('label.status.s0'), books_create_path(
              :title => book.title,
              :author => book.author,
              :isbn => book.isbn,
              :image_url => book.image_url,
              :url => book.url,
              :status => 0), # 気になる
              :method => :post,
              data: {confirm: "本棚に「#{t('label.status.s0')}」登録します."},
              class: 'register_book',
              remote: true%>
          </p>
          <p>
            <%=link_to t('label.status.s3'), books_create_path(
              :title => book.title,
              :author => book.author,
              :isbn => book.isbn,
              :image_url => book.image_url,
              :url => book.url,
              :status => 3), # 購入済
              :method => :post,
              data: {confirm: "本棚に「#{t('label.status.s3')}」登録します."},
              class: 'register_book',
              remote: true%>
          </p>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/books/_search_form.html.erb
<%= form_tag('/books/search', :remote => true, :class => 'form-inline') do%>
  本の登録
  <div class='form-group'><%=text_field_tag(:book, "", :name => 'title', :class => 'input-sm', :tabindex => '1', :placeholder => 'タイトル')%></div>
  <div class='form-group'><%=text_field_tag(:book, "", :name => 'author', :class => 'input-sm', :tabindex => '2', :placeholder => '著者')%></div>
  <div class='form-group'><%=submit_tag("検索", :class => 'btn btn-sm', :tabindex => '3')%></div>
<%end%>

app/views/books/create.js.erb
// 登録成功した場合、本棚に遷移するか確認する
<%if flash[:success].present?%>
  if (confirm('本棚を表示しますか？')) {
    location.href = '/books';
  }
<%end%>
// flashメッセージを出力し、3秒で消す
<%flash.each do |message_type, message|%>
  $('#flash-message').html('<div class="alert alert-<%=message_type%>"><%=message.html_safe%></div>');
<%end%>
$('.alert').delay(2500).fadeOut(500);

app/views/books/display_search.html.erb
<nav class="navbar navbar-default navbar-fixed-top2">
  <div class="container">
    <%= render 'search_form', class: 'navbar-form'%>
  </div>
</nav>
<!-- メモ作成フォーム -->
<p>
  検索結果：
  <span id="search_result_count">0</span>件
  <span id="total_count"></span>
</p>
<div id="search_result"></div>

app/views/books/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top2">
  <div class="container">
    <div class="nabvar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsed-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#top">
        本棚<span class="badge"><%=@books.count%></span>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="collapsed-menu">
      <ul class="nav navbar-nav">
        <li role="presentation"><a href="#books7"><%=t 'label.status.s7'%><span class="badge"><%=@books_status_7.count%></span></a><li>
        <li role="presentation"><a href="#books3"><%=t 'label.status.s3'%><span class="badge"><%=@books_status_3.count%></span></a><li>
        <li role="presentation"><a href="#books0"><%=t 'label.status.s0'%><span class="badge"><%=@books_status_0.count%></span></a><li>
        <li role="presentation"><a href="#books9"><%=t 'label.status.s9'%><span class="badge"><%=@books_status_9.count%></span></a><li>
        <li role="presentation"><%=link_to "登録する本を探す", '/books/search'%><li>
      </ul>
    </div>
  </div>
</nav>
<div id="books">
  <div id="top"></div>
  <!--各divをページ内ジャンプ位置調整用のdivで挟む-->
  <div class="adj"><div id="books7" class="jmp-to"><%=render partial: 'books', locals: {books: @books_status_7, status: 7}%></div></div>
  <div class="adj"><div id="books3" class="jmp-to"><%=render partial: 'books', locals: {books: @books_status_3, status: 3}%></div></div>
  <div class="adj"><div id="books0" class="jmp-to"><%=render partial: 'books', locals: {books: @books_status_0, status: 0}%></div></div>
  <div class="adj"><div id="books9" class="jmp-to"><%=render partial: 'books', locals: {books: @books_status_9, status: 9}%></div></div>
</div>

app/views/books/search.js.erb
var searchResultHtml = "";
var count = 0;
<%if @error_flg != 1%>
  <%if @books.present?%>
    searchResultHtml = '<%=j render :partial => "books_searched", :collections => @books%>';
    count = <%=@books.length%>
  <%end%>
  $('#search_result').html(searchResultHtml);
  $('#search_result_count').html(count);
  $('#total_count').html("/" + <%=@totalCount%> + "件");
<%end%>
<%flash.each do |message_type, message|%>
  $('#flash-message').html('<div class="alert alert-<%=message_type%>"><%=message.html_safe%></div>');
<%end%>
$('.alert').delay(2500).fadeOut(500);