config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books', to: 'books#index'
  get 'books/search', to: 'books#display_search'
  post 'books/search', to: 'books#search'
  post 'books/create', to: 'books#create'
  post 'books/update', to: 'books#status_update'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  get 'users/setting', to: 'users#display_setting'
  patch 'users/setting', to: 'users#update_setting'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TsundokuMgr", books_path, id: "logo"%>
    <div class="dropdown pos-left">
        <%if user_signed_in?%>
          <a href="#" class="dropdown-togle" data-toggle="dropdown" data-target="dropdown-menu">
            <%=current_user.name%><b class="catet"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Setting', users_setting_path, :class => 'navbar-link' %>
            </li>
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            </li>
          </ul>
        <%else%>
          <a href="#" class="dropdown-togle" data-toggle="dropdown" data-target="dropdown-menu">
            menu<b class="catet"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'%>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
            </li>
            <li>
              <%= link_to "Sign in with Twitter", user_twitter_omniauth_authorize_path, :class => 'navbar-link' %>
            </li>
          </ul>
        <%end%>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsundokuManager</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="mobile-web-app-capable" content="yes">
    <script type="text/javascript">
      $(function(){
        $('.alert').delay(2500).fadeOut(500);
      });
    </script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash-message">
        <%flash.each do |message_type, message|%>
          <div class="alert alert-<%=message_type%>"><%=message.html_safe%></div>
        <%end%>
      </div>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>